/* LoginPanel.java */
/* Login Component for the Hotel Management System
 *
 * Copyright 2016 Ankit Pati <ankitpati@gmail.com>
 *
 * This  software is  free software;  you can redistribute it and/or  modify  it
 * under the terms of the  GNU Lesser General Public License as published by the
 * Free Software Foundation;  either  version 3  of the  License,  or  (at  your
 * option) any later version.
 *
 * This software is distributed in the hope that it will be useful, but  WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 *
 * You  should  have received a copy of the GNU Lesser  General  Public  License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 */

package hotelmgmt;

import java.awt.event.*;
import javax.swing.*;

public class HMSFrame extends javax.swing.JFrame {
    final static long serialVersionUID = 0l;
    JPanel currentPanel = new LoginPanel();
    static HMSFrame self;

    public HMSFrame() {
        JMenuItem themeMenuItem;
        initComponents();

        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            themeMenu.add(themeMenuItem = new JMenuItem(info.getName()));
            themeMenuItem.addActionListener((ActionEvent evt) -> themeActionPerformedHandler(evt));
            if ("Nimbus".equals(themeMenuItem.getText())) themeMenuItem.doClick();
        }

        add(currentPanel);
        pack();
        setVisible(true);
    }

    private void themeActionPerformedHandler(ActionEvent evt) {
        SwingUtilities.invokeLater(() -> {
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
                    if (evt.getActionCommand().equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                SwingUtilities.updateComponentTreeUI(this);
                pack();
            }
            catch (Exception ex) {
                System.err.println("Cannot set "+evt.getActionCommand()+" theme.");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HMSFrameMenuBar = new javax.swing.JMenuBar();
        themeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management System");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        themeMenu.setText("Theme");
        HMSFrameMenuBar.add(themeMenu);

        setJMenuBar(HMSFrameMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void renderLogin(String username) {
        SwingUtilities.invokeLater(() -> {
            remove(currentPanel);
            add(currentPanel = new LoginPanel(username));
            pack();
        });
    }

    public final void renderAdmin(String username) {
        SwingUtilities.invokeLater(() -> {
            remove(currentPanel);
            add(currentPanel = new AdminPanel(username));
            pack();
        });
    }

    public final void renderUser(String username) {
        SwingUtilities.invokeLater(() -> {
            remove(currentPanel);
            add(currentPanel = new UserPanel(username));
            pack();
        });
    }

    public static void main(String args[]) {
        self = new HMSFrame();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar HMSFrameMenuBar;
    private javax.swing.JMenu themeMenu;
    // End of variables declaration//GEN-END:variables
}
/* end of HMSFrame.java */
