/* HMSFrame.java */
package hotelmgmt;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class HMSFrame extends javax.swing.JFrame {
    final static long serialVersionUID = 0l;
    JPanel currentPanel = new LoginPanel();
    static HMSFrame self;

    public HMSFrame() {
        JMenuItem themeMenuItem;
        initComponents();

        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            themeMenu.add(themeMenuItem = new JMenuItem(info.getName()));
            themeMenuItem.addActionListener((ActionEvent evt) -> themeActionPerformedHandler(evt));
            if ("Nimbus".equals(themeMenuItem.getText())) themeMenuItem.doClick();
        }

        add(currentPanel);
        pack();
        setVisible(true);
        SwingUtilities.invokeLater(() -> setLocationRelativeTo(null));
    }

    private void themeActionPerformedHandler(ActionEvent evt) {
        SwingUtilities.invokeLater(() -> {
            Point frameLocation;
            frameLocation = getLocation();
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
                    if (evt.getActionCommand().equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                SwingUtilities.updateComponentTreeUI(this);
                pack();
            }
            catch (Exception ex) {
                System.err.println("Cannot set " + evt.getActionCommand() + " theme.");
            }
            setLocation(frameLocation);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HMSFrameMenuBar = new javax.swing.JMenuBar();
        themeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management System");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        themeMenu.setText("Theme");
        HMSFrameMenuBar.add(themeMenu);

        setJMenuBar(HMSFrameMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void renderLogin(String username) {
        SwingUtilities.invokeLater(() -> {
            remove(currentPanel);
            add(currentPanel = new LoginPanel(username));
            pack();
        });
    }

    public final void renderAdmin(String username) {
        SwingUtilities.invokeLater(() -> {
            remove(currentPanel);
            add(currentPanel = new AdminPanel(username));
            pack();
        });
    }

    public final void renderUser(String username) {
        SwingUtilities.invokeLater(() -> {
            remove(currentPanel);
            add(currentPanel = new UserPanel(username));
            pack();
        });
    }

    public static void main(String args[]) {
        self = new HMSFrame();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar HMSFrameMenuBar;
    private javax.swing.JMenu themeMenu;
    // End of variables declaration//GEN-END:variables
}
/* end of HMSFrame.java */
