/* LoginPanel.java */
package hotelmgmt;

import java.awt.*;
import java.sql.*;
import javax.swing.*;

public class LoginPanel extends javax.swing.JPanel {
    final static long serialVersionUID = 0l;

    public LoginPanel() {
        initComponents();

        usernameField.setTransferHandler(null);
        passwordField.setTransferHandler(null);
    }

    public LoginPanel(String username) {
        this();
        usernameField.setText(username);
        usernameField.setForeground(Color.BLACK);
        SwingUtilities.invokeLater(() -> passwordField.grabFocus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        activityLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        adminCheckbox = new javax.swing.JCheckBox();
        errorLabel = new javax.swing.JLabel();

        headerLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Hotel Management System");

        activityLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 30)); // NOI18N
        activityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activityLabel.setText("Login");

        usernameField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        usernameField.setForeground(java.awt.Color.gray);
        usernameField.setText("Username");
        usernameField.setToolTipText("Username");
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        passwordField.setForeground(java.awt.Color.gray);
        passwordField.setText("Password");
        passwordField.setToolTipText("Password");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        adminCheckbox.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        adminCheckbox.setText("Login as Administrator");

        errorLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField)
                    .addComponent(activityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(activityLabel)
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        errorLabel.setText("");
        errorLabel.setForeground(Color.RED);
        usernameField.setText("Username");
        usernameField.setForeground(Color.GRAY);
        passwordField.setText("Password");
        passwordField.setForeground(Color.GRAY);
        adminCheckbox.setSelected(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        if ("".equals(usernameField.getText()) || usernameField.getForeground() == Color.GRAY) {
            usernameField.setForeground(Color.GRAY);
            usernameField.setText("Username");
        }
    }//GEN-LAST:event_usernameFieldFocusLost

    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
        if (usernameField.getForeground() == Color.GRAY) {
            usernameField.setText("");
            usernameField.setForeground(Color.BLACK);
            usernameField.setCaretPosition(0);
        }
    }//GEN-LAST:event_usernameFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if ("".equals(passwordField.getText()) || passwordField.getForeground() == Color.GRAY) {
            passwordField.setForeground(Color.GRAY);
            passwordField.setText("Password");
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (passwordField.getForeground() == Color.GRAY) {
            passwordField.setText("");
            passwordField.setForeground(Color.BLACK);
            passwordField.setCaretPosition(0);
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username;
        ResultSet rs;

        if (usernameField.getForeground() == Color.GRAY || "".equals(usernameField.getText())
                || passwordField.getForeground() == Color.GRAY || "".equals(passwordField.getText())) {
            errorLabel.setText("Provide Username and Password");
            errorLabel.setForeground(Color.RED);
            return;
        }

        try (
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/hotelmgmt", "hotelmgmt", "hotelmgmt");
            PreparedStatement ps = con.prepareStatement("select admin from users where username=? and password=?")
        ) {
            ps.setString(1, username = usernameField.getText());
            ps.setString(2, passwordField.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                if (adminCheckbox.isSelected()) {
                    if (rs.getByte(1) == (byte)1) {
                        HMSFrame.self.renderAdmin(username);
                        errorLabel.setText("Logged In");
                        errorLabel.setForeground(Color.BLUE);
                    }
                    else {
                        errorLabel.setText("Insufficient Privileges");
                        errorLabel.setForeground(Color.RED);
                    }
                }
                else {
                    HMSFrame.self.renderUser(username);
                    errorLabel.setText("Logged In");
                    errorLabel.setForeground(Color.BLUE);
                }
            }
            else {
                errorLabel.setText("Incorrect Credentials");
                errorLabel.setForeground(Color.RED);
            }
        }
        catch(SQLException e) {
            errorLabel.setText("Database Connection Failed");
            errorLabel.setForeground(Color.ORANGE);
        }
        finally {
            passwordField.setText("Password");
            passwordField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLabel;
    private javax.swing.JCheckBox adminCheckbox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
/* end of LoginPanel.java */
